---
- name: "Configure firewall"
  tags:
    - service
    - service.firewall
  import_tasks: firewall.yml
  when: service_firewalld | length > 0

- name: "Update service state"
  tags:
    - service
    - service.state
  import_tasks: state.yml
